#!/bin/bash

version=1.0

echo -e "FLAC2MP3 v$version\n(c) 2025, Alex Free (3-BSD)\n"

if ! command -v ffmpeg &> /dev/null; then
    if command -v dnf &> /dev/null || command -v apt &> /dev/null; then
        echo "Dependencies for FLAC2MP3 will be installed, which requires root privileges."
    fi

    if command -v dnf &> /dev/null; then
        sudo dnf update -y
        sudo dnf -y install ffmpeg
    elif command -v apt &> /dev/null; then
        sudo apt update --yes
        sudo apt install --yes ffmpeg
    else
        echo "Error: neither the dnf apt package managers are installed on your system meaning FLAC2MP3 can not install ffmpeg automatically."
        exit 1
    fi
fi

if [ -z "$1" ]; then

    echo "Usage: 
flac2mp3 <input folder>

<input folder>      Folder of FLAC files."
    
    exit 0
fi

if [ ! -d "${1}" ]; then
    echo "Can not find the input directory: \""${1}"\""
    exit 1
fi

cd "${1}"
parent=$(basename "${1}")
rm -rf "${parent}"
mkdir "${parent}"

# Find all .flac files recursively in the current directory
for f in *; do

  if [[ "${f}" == *.flac ]]; then
    # Set the output mp3 path
    mp3_file=$(basename "${f%.*}")

    # Convert using ffmpeg: -qscale 0 for best quality, -b:a 320k for 320 kbps bitrate
    ffmpeg -i "${f}" -qscale:a 0 -b:a 320k "${parent}"/"${mp3_file}".mp3

    echo "Converted $flac_file to $mp3_file"
   elif [[ "${f}" != "${parent}" ]]; then
     cp -r "${f}" "${parent}" 2>/dev/null
   fi
done

echo -e \n\n
ls -l "${parent}"

